name: PlatformIO Environment

on: 
  push:
    branches:
      - "*"
  release:
    types: [created]

jobs:
  build:
    name: PlatformIO Default Environment Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO for Bluepill
      run: platformio run -d ${{ github.workspace }}
  release:
    name: Store Release artifacts
    runs-on: ubuntu-latest
    if: github.event == "release"
    
    needs: "build"
    steps:
      - name: Gather the Release artifacts
        shell: bash  
        run: ${{ github.workspace }}/.github/copy-release-files.sh
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '.github/releasefiles/*'